### ISSUE TITLE
mapper_parsing_exception

### ISSUE THREAD

**Issue by hegebharat** [jtibshirani/text-embeddings#7]
RequestError: RequestError(400, 'mapper_parsing_exception', 'No handler for type [dense_vector] declared on field [title_vector]')
I got above error. So what could be the issue?
I am using 7.4 version elastic search and 
my index file look link
{

  "settings": {

    "number_of_shards": 2,

    "number_of_replicas": 1

  },

   "mappings": {

    "dynamic": "true",

    "_source": {

      "enabled": "true"

    },

    "properties": {

      "type": {

        "type": "keyword"

      },
        
   "title_vector": {
        "type": "dense_vector",
        "dims": 512
      }

    }

  }

}

**Comment by dianags** [comment]
Hi @hegebharat . Dk if you are still having this problem, but if you do, can you share an example of how your data looks like? Without it, it is hard to tell whether your problem is related to your mapping definition or your data format. Especially if you are trying to index data using python's elasticsearch library.

**Comment by hegebharat** [comment]
I got the answer. Elastic version i was using does not have xpack installed. Because of that I was facing the error.

Thanks
